[phases.setup]
nixPkgs = ["nodejs", "npm", "chromium"]

[phases.install]
cmds = [
  "cd server && npm ci",
  "cd client && npm ci"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "cd server && npm run build"
]

[start]
cmd = "cd server && npm run start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*/bin/chromium"